### ISSUE TITLE
script problems

### ISSUE THREAD

**Issue by boerti71** [philippelt/netatmo-api-python#26]
Hi, when I'm using simpleLastData, I got the following error:
pi@pfupfweb:~/netatmo-api-python/samples $ python simpleLastData
Traceback (most recent call last):
  File "simpleLastData", line 12, in <module>
    authorization = lnetatmo.ClientAuth()
  File "/usr/local/lib/python2.7/dist-packages/lnetatmo.py", line 157, in __init__
    if not resp: raise AuthFailure("Authentication request rejected")
lnetatmo.AuthFailure: Authentication request rejected

the access is working with php...

**Comment by boerti71** [comment]
problem solved, found out to change : 
File "/usr/local/lib/python2.7/dist-packages/lnetatmo.py"
