### ISSUE TITLE
lnetatmo runs into an error after some hours (2)

### ISSUE THREAD

**Issue by schroepfer** [philippelt/netatmo-api-python#27]
Hello, 
i wrote this in issue #21, but nothing i did, worked for me.

Here is my Code:
`channel_id = 325338 # PUT CHANNEL ID HERE
write_key  = 'RZxxxxxx...' # PUT YOUR WRITE KEY HERE
read_key   = 'P9N........' # PUT YOUR READ KEY HERE

DEBUG = False

while True:
    authorization = lnetatmo.ClientAuth()
    weatherData = lnetatmo.WeatherStationData(authorization)
    theData = weatherData.lastData()

    tempWZ = theData['Wohnzimmer']['Temperature']
    co2WZ = theData['Wohnzimmer']['CO2']
#    lautWZ = theData['Wohnzimmer']['Noise']
    tempStudio = theData['Studio']['Temperature']
    co2Studio = theData['Studio']['CO2']
    tempAussen = theData['AuÃŸen']['Temperature']
    rain24 = theData['Regensensor']['sum_rain_24']
    lastDa = theData['Wohnzimmer']['When']
    lastTime = time.strftime("%H:%M:%S",time.localtime(lastDa))

    if DEBUG:
        print(weatherData.lastData())
        print('Available modules : ', theData.keys() )
        print ('Temperatur im WZ : ', tempWZ )
        print('CO2 im WZ : ', co2WZ )
#        print('Lautst. im WZ : ', lautWZ )
        print('Temperatur im Studio : ', tempStudio )
        print('Temperatur drauÃŸen : ', tempAussen )
        print('Regen : ', rain24 )
        print ('letzte Daten im WZ : ', lastTime, lastDa )

    # Send the data to Thingspeak
    r = requests.post('https://api.thingspeak.com/update.json', data = {'api_key':write_key, 'field1':tempWZ, 'field2':co2WZ, 'field3':tempStudio, 'field4':co2Studio, 'field5':tempAussen, 'field7':rain24, 'field8':lastTime})
    # entnommen: 'field6':lautWZ,
    
    # wait 15 min.
    time.sleep (1800)
`
and after some time, i get this error:
_**Traceback (most recent call last):
  File "/home/pi/netatmo-api-python/write_NetAtmo_to_ThingSpeak_debug.py", line 14, in <module>
    weatherData = lnetatmo.WeatherStationData(authorization)
  File "/home/pi/netatmo-api-python/lnetatmo.py", line 260, in __init__
    self.rawData = resp['body']['devices']
TypeError: 'NoneType' object is not subscriptable
>>>**_

**Comment by philippelt** [comment]
To keep code simple, I do not try to catch all Netatmo possible errors, even including rate limiting.

I do not have applications that run continuously interacting with Netatmo servers. I rather use several alarm tasks, that runs as single shot every half an hour, and take actions depending on temperature.

Periodically, one of these tasks will fail because of any possible failure scenario. My wifi may be disturbed for some seconds precisely at the time the request is sent, my internet access can be down for a few seconds or minutes, my provider DNS may fail to resolve the server names, the Netatmo server may be unreachable for whatever reason (unfortunately, not unusual), etc... The service chain is so long that there are many possible failure scenarios.

In case of error, my programs just gave up as they will be restarted on the next time slot.

This issue of complex service chain is the reason why I switched to Zwave based temperature monitoring for any critical monitoring requirement. My server is directly connected to the sensor using just a Zwave controller USB key, nothing else, not even the LAN or Wifi. For 3 years now, I have been impressed by the reliability of this setup !

**Comment by schroepfer** [comment]
I think, you are right! The rest of my smarthome is running on EQ3 Hommatic. I think the stability ist nearly the same, than zWave. This works.
I'l give up with Netatmo!
Thank you!
