### ISSUE TITLE
Auto-test not correctly executing

### ISSUE THREAD

**Issue by JurgenLB** [philippelt/netatmo-api-python#66]
Auto-test is not functioning due to 'class HomesData' 

`lnetatmo - WARNING: Your current token scope do not allow access to Module
None
Traceback (most recent call last):
  File "/Users/jurgenlauwers/lNetatmo.py", line 1184, in <module>
    homesdata = HomesData(authorization)
  File "/Users/jurgenlauwers/lNetatmo.py", line 976, in __init__
    self.rawData = resp['body']['homes']
TypeError: 'NoneType' object is not subscriptable`

if I change
`homesdata = HomesData(authorization`
to
`homesdata = HomesData(authorization, homeid)`
and provide the correct homeid then the auto-test is correctly executed

**Comment by JurgenLB** [comment]
resolved #69
