### ISSUE TITLE
code=400, reason=, body=b'{"error":"invalid_client"}'

### ISSUE THREAD

**Issue by vavallee-wp** [philippelt/netatmo-api-python#85]
Created a new app, populated .netatmo.credentials with the token and client_id and client_secret.
python3 lnetatmo.py

Getting this error and not sure why.
```
code=400, reason=, body=b'{"error":"invalid_client"}'
Traceback (most recent call last):
  File "/Users/vincent.vallee/python/lnetatmo/netatmo-api-python/vtest.py", line 10, in <module>
    weatherData = lnetatmo.WeatherStationData(authorization)
                  ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "/Users/vincent.vallee/python/lnetatmo/netatmo-api-python/lnetatmo.py", line 416, in __init__
    self.getAuthToken = authData.accessToken
                        ^^^^^^^^^^^^^^^^^^^^
  File "/Users/vincent.vallee/python/lnetatmo/netatmo-api-python/lnetatmo.py", line 241, in accessToken
    if self.expiration < time.time() : self.renew_token()
                                       ^^^^^^^^^^^^^^^^^^
  File "/Users/vincent.vallee/python/lnetatmo/netatmo-api-python/lnetatmo.py", line 252, in renew_token
    if self.refreshToken != resp['refresh_token']:
                            ~~~~^^^^^^^^^^^^^^^^^
TypeError: 'NoneType' object is not subscriptable```

**Comment by vavallee-wp** [comment]
the app is "active"

**Comment by vavallee-wp** [comment]
So this problem self-resolved, and its working now.
I assume just a time delay from creating the app in netatmo?
