### ISSUE TITLE
Problem with Token renewal

### ISSUE THREAD

**Issue by fsneew** [philippelt/netatmo-api-python#86]
Hi there,

Every 10 minutes I use the library to get data from my weather station. Thanks for your work.
It works great but I have problems with the renewal of the token. I happened to me several times.

The logs:
code=400, reason=, body=b'{"error":"invalid_grant"}'
Traceback (most recent call last):
  File "/var/www/html/TOOLS/NetAtmo/NetAtmo.py", line 60, in auth
    weatherData = lnetatmo.WeatherStationData(authData)
                  ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "/usr/local/lib/python3.12/dist-packages/lnetatmo.py", line 416, in __init__
    self.getAuthToken = authData.accessToken
                        ^^^^^^^^^^^^^^^^^^^^
  File "/usr/local/lib/python3.12/dist-packages/lnetatmo.py", line 241, in accessToken
    if self.expiration < time.time() : self.renew_token()
                                       ^^^^^^^^^^^^^^^^^^
  File "/usr/local/lib/python3.12/dist-packages/lnetatmo.py", line 252, in renew_token
    if self.refreshToken != resp['refresh_token']:
                            ~~~~^^^^^^^^^^^^^^^^^
TypeError: 'NoneType' object is not subscriptable

Am I the only one having pbs with that ?
Thanks for helping

**Comment by philippelt** [comment]
Hello @fsneew ,

did you check that you are using the last release of the library and specify explicitly the path of the credentials file in the auth request ?

**Comment by fsneew** [comment]
Hello @philippelt,

Yes I'm using the last release, and I'm using the credentials file in my ~ directory. It works but after some time (couple of weeks) it doesn't work anymore. 

I wonder what happens when the token renew fails for some reason... I guess the renew token can be used only once.

**Comment by philippelt** [comment]
Could you try to specify the absolute path of your credential file when calling ClientAuth ? It seems that relative path are causing some unclear path expansion problems...

**Comment by fsneew** [comment]
I will try and will let you know

**Comment by nestorix1343** [comment]
Same problem here. Tried it with absolute path, does not make any difference.

**Comment by fsneew** [comment]
I tried something different ; just renew the token when expired. It seems to work better

**Comment by nestorix1343** [comment]
In the Netatmo Dev interface, there are 4 parameters:
- client ID
- client secret
- access token
- refresh token

The documentation of lnetatmo suggests to use client id, client secret and refresh token.

Then I get the "invalid grant" error.

When I use the access token instead of the client secret, I get the following error:

  File "/Users/marcel/projects/netatmo2mqtt/netatmo2mqtt.py", line 221, in process_netatmo_data
    module_list = weather_data.modulesNamesList()
                  ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "/Users/marcel/projects/netatmo2mqtt/venv/lib/python3.12/site-packages/lnetatmo.py", line 467, in modulesNamesList
    res.append(station['module_name'])
               ~~~~~~~^^^^^^^^^^^^^^^
TypeError: 'NoneType' object is not subscriptable

**Comment by tru7** [comment]
Sorry to bother but I'm quite desperate. I cloned today on a fresh system and generate a new refresh token for read_station. I'm using my old script using lnetamto.py in the local folder to get data using the credential file with absolute path and it works perfectly the first time. But when I run the script a second time I get the same errors as in the first post (invalid_grant). I repeated the procedure several times - it works the first time and never a second time. Permissions are fine because I edit the credential file with the same user as running the script.
I even reduced the script to a simple:
  authorization = lnetatmo.ClientAuth()
  weatherData = lnetatmo.WeatherStationData(authorization)
with and without the credentialFile argument resulting in the same problem.
What can I do?

**Comment by nestorix1343** [comment]
I use:

```
import lnetatmo

NETATMO_CREDENTIAL_FILE="/some/absolute/path/to/a/.credentialfile"
authorization = lnetatmo.ClientAuth(credentialFile=NETATMO_CREDENTIAL_FILE)
weather_data = lnetatmo.WeatherStationData(authorization)
last_data = weather_data.lastData()
```

The credentials file I created looks like:


```
$ cat /some/absolute/path/to/a/.credentialfile
{
 "CLIENT_ID": "client_id_string from netatmo dev site",
 "CLIENT_SECRET": "client_secret_string from netatmo dev site",
 "REFRESH_TOKEN": "refresh_token_string from netatmo dev site"
}

```

If you look at the file after the first start, did the "REFRESH_TOKEN" string change?

**Comment by nestorix1343** [comment]
I did not write the code, but I took a quick look at it. As far as I understand it, it will refresh the token on startup (and write it to the credentials file) and then every so many hours when the refresh token expires. This expiration time is returned by Netatmo so as soon as the lnetatmo notices that it is expired, it requests a new token and writes this.

So if you start the script, it should write the file with a new token.

When getting the new secrets and token I also made a mistake because on the Netatmo dev site, they present you 4 "tokens/secrets" ... I was messing with the wrong set. You need the client ID, client secret and refresh token (not the access token) (If I am not mistaken about the names).

On more verbose output, you could try to add some print statements in the library. Especially in lnetatmo.py and then on line 257-258, the credentials file is written on a renewal of the token (and a renewal is also forced upon first start). You could check if the code gets there at all.

I think the writing and reading of the credentials file could use an encoding argument but it works for me without it. What kind of system/OS are you using?

**Comment by tru7** [comment]
Thanks, I'll try to add some print statements to track the actions. My OS is Ubuntu 24.04.1

**Comment by tru7** [comment]
I think I found the problem in line 257: the if-clause is always False - therefore the credential file never gets written. If I remove the type() cast(?) from self, it works fine. Honestly I'm not familiar with python language but I wonder how that could work for anyone.

**Comment by nestorix1343** [comment]
I am using version 4.1.2 (just new) from PyPi (https://pypi.org/project/lnetatmo/)

Use that one, I think the main branch is development right now.

**Comment by tru7** [comment]
Agreed. The only difference is the last commit from 5 days ago - and that one triggers the problem. Hopefully it gets fixed before next release gets published.

**Comment by nestorix1343** [comment]
4.1.2 is working for me, so "if it ain't broke, do not upgrade it" 😀

**Comment by nestorix1343** [comment]
I do not see myself as a Python wizard, but I do think that

`if hasattr(type(self), "_credentialFile"):`

should be:

`if hasattr(self, "_credentialFile"):`

I did not test it (yet).

**Comment by philippelt** [comment]
Well, seems like I did not spent enough time on code review in the last months.

I started a whole review and cleanup and realized that there are multiple issues that needs to be fixed regarding thermostat and homecoach.

As I don't own any of these devices it will not be possible to test the code. There are some obvious things that can be fixed but it is always at risk to push untested code.

I just add these items to my, already very long, to do list :smiling_face_with_tear: 
If any one wants to contribute, welcome

**Comment by JurgenLB** [comment]
Thermostat and Homecoach are partly my work, can I help with that ?

**Comment by philippelt** [comment]
Hello @JurgenLB ,

you are very welcome to fix both sections. I have no access to such devices thus I can't do testing of this code but there are obvious troubles even without testing.

For example, in the ThermostatData class, the following code doesn't make sense as it will return the first relay without searching for the id parameter supplied (and the if clause is totally useless):
```python
    def Relay_Plug(self, _id=None):
        for Relay in self.rawData:
            if _id in Relay:
                return Relay
            else:
                #print (Relay['_id'])
                return Relay
```
During my last code review, I tried to put some `#FIXME` comments in places where I located obvious bugs. You could start by looking at these places but a deep review of the whole code for these two classes would probably be required.

Thanks in advance
