### ISSUE TITLE
AttributeError: 'NoneType' object has no attribute 'items'

### ISSUE THREAD

**Issue by AFI4711** [philippelt/netatmo-api-python#91]
Now I get the following error everytime when calling:

```
for station in weather.stations:
    for module, moduleData in weather.lastData(station=station, exclude=3600).items() :
...
...
Traceback (most recent call last):
  File "/home/andi/Computer/src/python/netatmo-neu/netatmo-api-python-master/./printAllLastDataJSON.py", line 37, in <module>
    for module, moduleData in weather.lastData(station=station, exclude=3600).items() :
AttributeError: 'NoneType' object has no attribute 'items'

```

**Comment by AFI4711** [comment]
After a new installation today, a similiar error occurs when runnning the test _simpleLastData.py_:

```
./simpleLastData.py 
Traceback (most recent call last):
  File "/home/andi/netatmo_neu/netatmo-api-python-master/./simpleLastData.py", line 16, in <module>
    ( devList.lastData()['internal']['Temperature'],
      ~~~~~~~~~~~~~~~~~~^^^^^^^^^^^^
TypeError: 'NoneType' object is not subscriptable

```

**Comment by AFI4711** [comment]
**Another simple Test shows a similiar error:**
_simpleTest.py_:
```
import lnetatmo

authorization = lnetatmo.ClientAuth()

weather = lnetatmo.WeatherStationData(authorization)
user = weather.user
print("Station owner : ", user.mail)
print("Data units    : ", user.unit)

devList = lnetatmo.WeatherStationData(authorization)

print ("Current temperature (inside/outside): %s / %s °C" %
        ( devList.lastData()['Weather Station']['Temperature'],
          devList.lastData()['Outdoor Module']['Temperature'])
      )
```
**the error:**

```
./simpleTest.py 
Station owner :  andreas@finkel.de
Data units    :  metric
Traceback (most recent call last):
  File "/home/andi/docker/netatmo_neu/netatmo-api-python-master/./simpleTest.py", line 27, in <module>
    ( devList.lastData()['Weather Station']['Temperature'],
      ~~~~~~~~~~~~~~~~~~^^^^^^^^^^^^^^^^^^^
TypeError: 'NoneType' object is not subscriptable



```

**Comment by philippelt** [comment]
This is the behavior you would have if you don't have any weather station in your account (or that you scope do not allow to find them).

**Comment by AFI4711** [comment]
Strange, I'll use your software a long time running successfully. 
Perhaps there are some problems with **Netatmo**.
I'll create new credentials and try again. Many thanks so far.

**Comment by AFI4711** [comment]
Generation of new TOKENS and/or CLIENT_IDs brought no improvement.
Since I found no data of my "Weather Station" on Netatmo Homepage (https://home.netatmo.com/control/dashboard ) I restarted the Weather Station (since new. Now everything is running fine.
This is so embarrassing, sorry for the Inconveniences.
