### ISSUE TITLE
Error connection

### ISSUE THREAD

**Issue by kurb77** [philippelt/netatmo-api-python#95]
Hello,
for a few days I can no longer connect to the API. Anything to change? I am using a version of the lnetatmo API that is not up to date, is that why?
Thanks

`code=400, reason=, body=b'{"error":"invalid_grant"}'
Traceback (most recent call last):
  File "/home/domoticz/myscript/netatmo.py", line 69, in <module>
    thermostat = lnetatmo.ThermostatData(authorization)
  File "/myscript/lnetatmo.py", line 357, in __init__
    self.getAuthToken = authData.accessToken
  File "/myscript/lnetatmo.py", line 241, in accessToken
    if self.expiration < time.time() : self.renew_token()
  File "/myscript/lnetatmo.py", line 252, in renew_token
    if self.refreshToken != resp['refresh_token']:
TypeError: 'NoneType' object is not subscriptable
`

**Comment by philippelt** [comment]
The error is `"error":"invalid_grant"`
Recreate your access+refresh token for your apps and update your credential file.

It would be better to use an up to date release of the library. The current version still support python 2 if this is why you are afraid to update...

Happy Christmas!

**Comment by kurb77** [comment]
ok, i will try
thank you
happy Christmas too

**Comment by kurb77** [comment]
I Recreated my access+refreshed token and updated the library, all work, thank you.
i  added some fonctions on the library for the thermostat, it is possible to add on the ref ?

```
#on class ThermostatData:
def Thermostat_DataByName(self,name=None):
def Relay_Plug(self, _id=None,module_name=None):
def getIdplaningActif(self,name=None):
def getNameplaningActif(self,name=None):
def setPlaningById(self, home_id=None, program_id=None):
def update(self):
def getPlaningActifByName(self, name=None):
```

thank you

**Comment by philippelt** [comment]
Hello @kurb77 ,
sorry for the huge delay, I am again running out of free time for the moment.

Many thanks for your suggestion.

If you want to submit code to the library, fell free to create a pull request with the proposed changes.
Please, update the documentation for any new function added and, if possible, some example code to illustrate their use.
I will not merge code proposal if the associated documentation is not created/updated.
